### ISSUE TITLE
Build error: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by sirkrisp** [davidwinter/electron-forge-maker-snap#122]
Hi,

unfortunately I also get build errors:

```
  electron-forge-maker-snap:snap-packager Snapcraft stdout: Launching a VM.
  electron-forge-maker-snap:snap-packager  +865ms
  electron-forge-maker-snap:snap-packager Snapcraft stdout: Sorry, an error occurred in Snapcraft:
  electron-forge-maker-snap:snap-packager  +0ms
  electron-forge-maker-snap:snap-packager Snapcraft stdout: Traceback (most recent call last):
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/bin/snapcraft", line 8, in <module>
  electron-forge-maker-snap:snap-packager     sys.exit(run())
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
  electron-forge-maker-snap:snap-packager     return self.main(*args, **kwargs)
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/click/core.py", line 1062, in main
  electron-forge-maker-snap:snap-packager     rv = self.invoke(ctx)
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
  electron-forge-maker-snap:snap-packager     return _process_result(sub_ctx.command.invoke(sub_ctx))
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
  electron-forge-maker-snap:snap-packager     return ctx.invoke(self.callback, **ctx.params)
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/click/core.py", line 763, in invoke
  electron-forge-maker-snap:snap-packager     return __callback(*args, **kwargs)
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/cli/lifecycle.py", line 387, in snap
  electron-forge-maker-snap:snap-packager     _execute(steps.PRIME, parts=tuple(), pack_project=True, output=output, **kwargs)
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/cli/lifecycle.py", line 125, in _execute
  electron-forge-maker-snap:snap-packager     with build_provider_class(
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/internal/build_providers/_base_provider.py", line 87, in __enter__
  electron-forge-maker-snap:snap-packager     self.create()
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/internal/build_providers/_multipass/_multipass.py", line 161, in create
  electron-forge-maker-snap:snap-packager     self.launch_instance()
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/internal/build_providers/_base_provider.py", line 234, in launch_instance
  electron-forge-maker-snap:snap-packager     self._ensure_compatible_build_environment()
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/internal/build_providers/_base_provider.py", line 335, in _ensure_compatible_build_environment
  electron-forge-maker-snap:snap-packager     if self._check_environment_needs_cleaning():
  electron-forge-maker-snap:snap-packager   File "/snap/snapcraft/7201/lib/python3.8/site-packages/snapcraft/internal/build_providers/_base_provider.py", line 298, in _check_environment_needs_cleaning
  electron-forge-maker-snap:snap-packager     provider_base = info.get("base")
  electron-forge-maker-snap:snap-packager AttributeError: 'NoneType' object has no attribute 'get'
  electron-forge-maker-snap:snap-packager You can find the traceback in file '/tmp/tmpuj6cwes4/trace.txt'.
  electron-forge-maker-snap:snap-packager  +1ms
  electron-forge-maker-snap:snap-packager Snapcraft has finished running, with a status code of: 1 +56ms
  electron-forge-maker-snap:snap-packager Snapcraft exited with a non-zero status code of: 1 +1ms
```

Not sure whether this is related to your project..

**Comment by sirkrisp** [comment]
For anyone else having issues with electron forge and snap. I wasted hours with this and its much easier to just use electron-builder as officially recommended by snapcraft

- https://snapcraft.io/docs/electron-apps
- https://www.electron.build/configuration/snap
