### ISSUE TITLE
Gtk.warning cannot open display :0

### ISSUE THREAD

**Issue by arthyn** [davidwinter/electron-forge-maker-snap#51]
Seems like this is a known issue with Electron trying to use wayland, currently experiencing it in Debian 10.9 when trying to run. Here's a fix that was applied in Electron Builder:
https://github.com/electron-userland/electron-builder/commit/2278c2a

**Comment by davidwinter** [comment]
Hi @arthyn - can you try with `v1.0.3` please? I've added the fixes that `electron-builder` added to their system, so :crossed_fingers: that does the trick.

**Comment by arthyn** [comment]
Getting this from Forge:

```
An unhandled rejection has occurred inside Forge:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/hunter/Projects/native-urbit/node_modules/@davidwinter/electron-forge-maker-snap/index.js
require() of ES modules is not supported.
require() of /Users/hunter/Projects/native-urbit/node_modules/@davidwinter/electron-forge-maker-snap/index.js from /Users/hunter/Projects/native-urbit/node_modules/@electron-forge/core/dist/util/require-search.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/hunter/Projects/native-urbit/node_modules/@davidwinter/electron-forge-maker-snap/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1126:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at requireSearchRaw (/Users/hunter/Projects/native-urbit/node_modules/@electron-forge/core/src/util/require-search.ts:15:14)
    at _default (/Users/hunter/Projects/native-urbit/node_modules/@electron-forge/core/src/util/require-search.ts:33:18)
    at _default (/Users/hunter/Projects/native-urbit/node_modules/@electron-forge/core/src/api/make.ts:123:26)
    at /Users/hunter/Projects/native-urbit/node_modules/@electron-forge/cli/src/electron-forge-make.ts:44:5 {
  code: 'ERR_REQUIRE_ESM'
}

Electron Forge was terminated. Location:
{}
```

**Comment by davidwinter** [comment]
Ah, it seems I was a little too keen on converting the package to use ESM. Electron isn't quite there yet in terms of [support](https://github.com/electron/electron/issues/21457). I've now reverted back to CJS, so can you please try again with `2.0.0`?

**Comment by davidwinter** [comment]
@arthyn sorry found a few more bugs! `2.0.3` should be good to go now if you're able to try again.

**Comment by arthyn** [comment]
@davidwinter I was testing this for a big release so I forgot to come back and comment, but everything is working and looks good thanks!
