### ISSUE TITLE
Snap still fails to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by abulka** [davidwinter/electron-forge-maker-snap#70]
@davidwinter tried your maker referred to in https://github.com/electron-userland/electron-installer-snap/issues/83 on my Ubuntu 20.04 VM running in Vmware with VT-x configured in Vmware processor settings. It took a long time but ultimately failed with

```
$ npm run make

> myapp@1.0.0 make
> electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets: snap
✖ Making for target: snap - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: snap
Snapcraft exited with a non-zero status code of: 2
Error: Snapcraft exited with a non-zero status code of: 2
    at ChildProcess.<anonymous> (/home/andy/Devel/electron-tests/myapp/node_modules/@davidwinter/electron-forge-maker-snap/snap-packager.js:132:13)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:675:12)
```

using the config

```json
        {
          "name": "@davidwinter/electron-forge-maker-snap",
          "config": {
            "categories": ["Utility"],
            "icon": "bacteria.png"
          }
        }
```

My system info

```
$ snapcraft --version
snapcraft, version 4.8.2

andy@ubuntu:~/Devel/electron-tests/myapp$ which snapcraft
/snap/bin/snapcraft

andy@ubuntu:~/Devel/electron-tests/myapp$ multipass --version
multipass  1.6.2
multipassd 1.6.2

andy@ubuntu:~/Devel/electron-tests/myapp$ multipass list
Name                    State             IPv4             Image
primary                 Running           10.240.47.137    Ubuntu 20.04 LTS
snapcraft-myapp         Delayed Shutdown  10.240.47.86     Ubuntu Snapcraft builder for Core 18

andy@ubuntu:~/Devel/electron-tests/myapp$ uname -v
#62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021
```

**Comment by davidwinter** [comment]
I've often received a status code of 2 from multipass, and relaunching multipass/restarting has sometimes resolved this. Have you given that a try already?

**Comment by rwwagner90** [comment]
@davidwinter I seem to be getting this error on Ubuntu 18 as well, all the sudden. I did updated some deps today, so perhaps something broke. Any ideas?
